'use client'

import { useState } from 'react'
import { ArrowLeft, Check, Loader2, Sparkles, Trash2 } from 'lucide-react'
import type { CaptureDraft, CaptureTemplate } from '@/lib/casa/types'
import { splitCapture } from '@/lib/casa/gemini'

export function CaptureView({ apiKey, templates, onCommit, onClose }: { apiKey: string; templates: CaptureTemplate[]; onCommit: (drafts: CaptureDraft[]) => void; onClose: () => void }) {
  const [text, setText] = useState(''); const [templateId, setTemplateId] = useState(templates.find((item) => item.isDefault)?.id ?? templates[0]?.id ?? ''); const [drafts, setDrafts] = useState<CaptureDraft[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const process = async () => { if (!text.trim()) return; setBusy(true); setError(''); try { const template = templates.find((item) => item.id === templateId); setDrafts(await splitCapture(apiKey, text, template?.promptText)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Capture gagal diproses.') } finally { setBusy(false) } }
  return <section className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-5 py-10 md:px-10 md:py-16"><header className="flex items-start justify-between gap-6"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">Intelligent intake</p><h1 className="mt-3 font-serif text-4xl text-balance md:text-6xl">Capture without sorting.</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">Paste a thought stream. Gemini separates it into atomic notes, estimates fields, and suggests connections before anything is saved.</p></div><button onClick={onClose} className="border border-border p-3" aria-label="Tutup capture"><ArrowLeft className="size-5" /></button></header>
    {!drafts.length ? <div className="flex flex-col gap-4"><div className="flex flex-wrap gap-3"><label className="text-sm text-muted-foreground">Template <select value={templateId} onChange={(event) => setTemplateId(event.target.value)} className="ml-2 border border-border bg-card px-3 py-2 text-foreground">{templates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><textarea autoFocus value={text} onChange={(event) => setText(event.target.value)} placeholder="Drop a meeting transcript, research notes, or a stream of thought here..." className="min-h-80 resize-y border border-border bg-card p-6 text-base leading-relaxed outline-none focus:border-primary" /><button disabled={busy || !text.trim()} onClick={() => void process()} className="flex w-fit items-center gap-2 bg-primary px-5 py-3 text-sm text-primary-foreground disabled:opacity-50">{busy ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}Split with Gemini</button>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}</div> : <div className="flex flex-col gap-4"><div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">Review {drafts.length} notes before saving.</p><button onClick={() => onCommit(drafts)} className="flex items-center gap-2 bg-primary px-5 py-3 text-sm text-primary-foreground"><Check className="size-4" />Save all notes</button></div>{drafts.map((draft, index) => <article key={index} className="border border-border bg-card p-5"><div className="flex items-start gap-4"><div className="flex min-w-0 flex-1 flex-col gap-3"><input aria-label={`Judul draft ${index + 1}`} value={draft.title} onChange={(event) => setDrafts((items) => items.map((item, i) => i === index ? { ...item, title: event.target.value } : item))} className="border-b border-border bg-transparent pb-2 font-serif text-2xl outline-none focus:border-primary" /><textarea aria-label={`Konten draft ${index + 1}`} value={draft.content} onChange={(event) => setDrafts((items) => items.map((item, i) => i === index ? { ...item, content: event.target.value } : item))} className="min-h-28 resize-y bg-transparent text-sm leading-relaxed outline-none" /><p className="text-xs text-muted-foreground">{draft.category} · {draft.noteType} · {draft.tags.join(', ')}</p></div><button aria-label={`Hapus draft ${index + 1}`} onClick={() => setDrafts((items) => items.filter((_, i) => i !== index))}><Trash2 className="size-4" /></button></div></article>)}</div>}
  </section>
}
