'use client'

import dynamic from 'next/dynamic'
import { useMemo, useRef, useState } from 'react'
import type { ForceGraphMethods, NodeObject } from 'react-force-graph-2d'
import { blendFieldColor } from '@/lib/casa/colors'
import type { Note } from '@/lib/casa/types'

const ForceGraph2D = dynamic(() => import('react-force-graph-2d'), { ssr: false })
export function GraphView({ notes, onOpen }: { notes: Note[]; onOpen: (note: Note) => void }) { const graphRef=useRef<ForceGraphMethods<NodeObject<Note>>|undefined>(undefined); const [category,setCategory]=useState('All'); const categories=['All',...Array.from(new Set(notes.map(n=>n.category)))]; const visible=category==='All'?notes:notes.filter(n=>n.category===category); const data=useMemo(()=>({nodes:visible.map(note=>({...note,name:note.title})),links:visible.flatMap(note=>note.links.map(title=>visible.find(item=>item.title.toLowerCase()===title.toLowerCase())).filter(Boolean).map(target=>({source:note.id,target:target!.id})))}),[visible]); const degree=(id:string)=>data.links.filter(link=>String((link.source as {id?:string})?.id??link.source)===id||String((link.target as {id?:string})?.id??link.target)===id).length; return <section className="relative min-h-[calc(100dvh-5rem)] overflow-hidden bg-background" aria-label="Knowledge graph"><div className="absolute left-5 top-5 z-10 flex flex-col gap-3 border border-border bg-card/95 p-4 shadow-xl backdrop-blur md:left-8 md:top-8"><div><p className="font-serif text-xl">Knowledge graph</p><p className="text-sm text-muted-foreground">{visible.length} notes · {data.links.length} connections</p></div><select aria-label="Filter category" value={category} onChange={e=>setCategory(e.target.value)} className="border border-border bg-background px-3 py-2 text-xs">{categories.map(item=><option key={item}>{item}</option>)}</select></div><ForceGraph2D ref={graphRef} graphData={data} backgroundColor="#0d0c0d" nodeLabel="title" nodeRelSize={7} linkColor={()=>'#30272a'} linkWidth={1.5} cooldownTicks={120} onNodeClick={node=>onOpen(node as Note)} nodeCanvasObject={(node,ctx,scale)=>{const item=node as NodeObject<Note>&Note;const radius=6+degree(item.id)*1.6;ctx.beginPath();ctx.arc(node.x!,node.y!,radius,0,Math.PI*2);ctx.fillStyle=blendFieldColor(item.fieldScores);ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=15;ctx.fill();ctx.shadowBlur=0;if(scale>1.15){ctx.font=`${12/scale}px Instrument Sans`;ctx.fillStyle='#f3eee9';ctx.textAlign='center';ctx.fillText(item.title,node.x!,node.y!+radius+14/scale)}}}/></section> }
