'use client'

import { useCallback, useEffect, useState } from 'react'
import { Menu } from 'lucide-react'
import { CasaSidebar } from './casa-sidebar'
import { NoteEditor } from './note-editor'
import { CasaOrb, speakEnglish } from './casa-orb'
import { CaptureView } from './casa/capture-view'
import { ChatView, FilesView, SearchView, SettingsView, TagsView, TemplatesView } from './casa/workspace-views'
import { GraphView } from './casa/graph-view'
import { deleteNote, deleteTemplate, loadNotes, loadTemplates, replaceSampleData, saveNote, saveTemplate } from '@/lib/casa/db'
import { parseVoiceIntent } from '@/lib/casa/gemini'
import { extractWikiLinks } from '@/lib/casa/links'
import type { CaptureDraft, CaptureTemplate, CasaSettings, CasaState, Note, WorkspaceView } from '@/lib/casa/types'

const defaultSettings:CasaSettings={apiKey:'',shortcut:'Ctrl+Shift+Space',voiceEnabled:true,voiceLocale:'en-US'}
const noteFromDraft=(draft:CaptureDraft):Note=>({...draft,id:crypto.randomUUID(),createdAt:Date.now(),updatedAt:Date.now(),links:extractWikiLinks(draft.content),aiMeta:draft.aiMeta??{}})

export function CasaWorkspace(){const[notes,setNotes]=useState<Note[]>([]),[templates,setTemplates]=useState<CaptureTemplate[]>([]),[selected,setSelected]=useState<Note|null>(null),[view,setView]=useState<WorkspaceView>('note'),[orbState,setOrbState]=useState<CasaState>('idle'),[mobileOpen,setMobileOpen]=useState(false),[settings,setSettings]=useState<CasaSettings>(defaultSettings)
  const refresh=useCallback(async()=>{const[loadedNotes,loadedTemplates]=await Promise.all([loadNotes(),loadTemplates()]);setNotes(loadedNotes);setSelected(current=>loadedNotes.find(n=>n.id===current?.id)??loadedNotes[0]??null);setTemplates(loadedTemplates)},[])
  useEffect(()=>{void refresh();const stored=window.localStorage.getItem('casa-settings');if(stored){try{setSettings({...defaultSettings,...JSON.parse(stored)})}catch{setSettings(defaultSettings)}}},[refresh])
  useEffect(()=>{window.localStorage.setItem('casa-settings',JSON.stringify(settings))},[settings])
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.ctrlKey&&event.shiftKey&&event.code==='Space'){event.preventDefault();window.dispatchEvent(new Event('casa-toggle'))}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[])
  const openNote=(note:Note)=>{setSelected(note);setView('note')};const updateNote=(note:Note)=>{const updated={...note,links:extractWikiLinks(note.content),updatedAt:Date.now()};setSelected(updated);setNotes(current=>current.map(item=>item.id===updated.id?updated:item));void saveNote(updated)}
  const commit=async(drafts:CaptureDraft[])=>{const created=drafts.map(noteFromDraft);await Promise.all(created.map(saveNote));setNotes(current=>[...created,...current]);setSelected(created[0]??null);setView('note')}
  const createBlank=()=>{const note=noteFromDraft({title:'Untitled note',content:'',tags:[],category:'Inbox',noteType:'live',fieldScores:{backend:0,frontend:0,aiEngineer:0,mlEngineer:0,devops:0,iot:0,network:0,instrumentationAutomation:0},links:[],aiMeta:{}});void saveNote(note);setNotes(current=>[note,...current]);openNote(note)}
  const removeSelected=async()=>{if(!selected||!window.confirm(`Delete “${selected.title}”?`))return;await deleteNote(selected.id);const remaining=notes.filter(n=>n.id!==selected.id);setNotes(remaining);setSelected(remaining[0]??null)}
  const handleVoice=useCallback(async(transcript:string)=>{try{const result=await parseVoiceIntent(settings.apiKey,transcript,selected,notes);if(result.intent==='NOTE_BARU'&&result.note){const note=noteFromDraft(result.note);await saveNote(note);setNotes(current=>[note,...current]);openNote(note)}else if(result.intent==='TAMBAH_KE_NOTE_AKTIF'&&selected&&result.appendText)updateNote({...selected,content:`${selected.content}\n\n${result.appendText}`}) ;else if(result.intent==='CARI_NOTE'){const query=(result.query??transcript).toLowerCase();const found=notes.find(n=>`${n.title} ${n.content}`.toLowerCase().includes(query));if(found)openNote(found)}else if(result.intent==='BRAINSTORM_CHAT')setView('chat');if(settings.voiceEnabled)speakEnglish(result.spokenResponse||'Done.',settings.voiceLocale,setOrbState);else{setOrbState('done');window.setTimeout(()=>setOrbState('idle'),900)}}catch(error){setOrbState('error');if(settings.voiceEnabled)speakEnglish(error instanceof Error?error.message:'I could not complete that request.',settings.voiceLocale,setOrbState)}},[notes,selected,settings])
  const reset=async()=>{if(!window.confirm('Replace local notes with the complete sample brain?'))return;await replaceSampleData();await refresh();setView('note')}
  let content:React.ReactNode;if(view==='capture')content=<CaptureView apiKey={settings.apiKey} templates={templates} onCommit={drafts=>void commit(drafts)} onClose={()=>setView('note')}/>;else if(view==='search')content=<SearchView notes={notes} onOpen={openNote}/>;else if(view==='files')content=<FilesView notes={notes} onOpen={openNote}/>;else if(view==='graph')content=<GraphView notes={notes} onOpen={openNote}/>;else if(view==='chat')content=<ChatView apiKey={settings.apiKey} notes={notes}/>;else if(view==='tags')content=<TagsView notes={notes} onOpen={openNote}/>;else if(view==='templates')content=<TemplatesView templates={templates} onSave={t=>{setTemplates(v=>[...v,t]);void saveTemplate(t)}} onDelete={id=>{setTemplates(v=>v.filter(t=>t.id!==id));void deleteTemplate(id)}}/>;else if(view==='settings')content=<SettingsView settings={settings} onChange={setSettings} onReset={()=>void reset()}/>;else content=selected?<NoteEditor note={selected} notes={notes} apiKey={settings.apiKey} onChange={updateNote} onOpenNote={openNote} onCreate={createBlank} onDelete={()=>void removeSelected()}/>:<div className="grid min-h-[80dvh] place-items-center"><button onClick={createBlank} className="bg-primary px-5 py-3 text-primary-foreground">Create your first note</button></div>
  return <div className="flex min-h-dvh bg-background text-foreground">{mobileOpen&&<button aria-label="Tutup navigasi" className="fixed inset-0 z-30 bg-background/80 md:hidden" onClick={()=>setMobileOpen(false)}/>}<CasaSidebar activeView={view} notes={notes} onNavigate={setView} onOpenNote={openNote} mobileOpen={mobileOpen} onClose={()=>setMobileOpen(false)}/><div className="min-w-0 flex-1"><header className="flex h-16 items-center gap-4 border-b border-border px-4 md:hidden"><button aria-label="Buka navigasi" onClick={()=>setMobileOpen(true)}><Menu className="size-5"/></button><span className="font-serif text-xl">CasaLabs.</span></header>{content}</div><CasaOrb state={orbState} onStateChange={setOrbState} onTranscript={handleVoice}/></div>}
