'use client'

import { Bot, FileText, Files, Hash, LayoutTemplate, Network, Plus, Search, Settings, X } from 'lucide-react'
import type { Note, WorkspaceView } from '@/lib/casa/types'

const nav = [['search','Search',Search],['files','Files',Files],['graph','Graph View',Network],['chat','Chat with AI',Bot],['tags','Tags',Hash],['templates','Templates',LayoutTemplate],['settings','Settings',Settings]] as const

export function CasaSidebar({ activeView, notes, onNavigate, onOpenNote, mobileOpen, onClose }: { activeView: WorkspaceView; notes: Note[]; onNavigate: (view: WorkspaceView) => void; onOpenNote: (note: Note) => void; mobileOpen: boolean; onClose: () => void }) {
  return <aside className={`fixed inset-y-0 left-0 z-40 flex w-72 flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground transition-transform md:static md:w-64 md:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex h-20 items-center justify-between border-b border-sidebar-border px-5"><button onClick={() => onNavigate('note')} className="font-serif text-2xl tracking-tight">Casa<span className="text-primary">.</span></button><button className="md:hidden" onClick={onClose} aria-label="Tutup navigasi"><X className="size-5" /></button></div><div className="p-3"><button onClick={() => { onNavigate('capture'); onClose() }} className="flex w-full items-center justify-center gap-2 bg-primary px-4 py-3 text-sm font-medium text-primary-foreground"><Plus className="size-4" />New capture</button></div><nav className="flex flex-col gap-1 px-3 pb-3" aria-label="Navigasi utama">{nav.map(([id,label,Icon]) => <button key={id} onClick={() => { onNavigate(id); onClose() }} aria-current={activeView === id ? 'page' : undefined} className={`flex items-center gap-3 px-3 py-2.5 text-left text-sm ${activeView === id ? 'bg-sidebar-accent text-sidebar-accent-foreground' : 'text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground'}`}><Icon className="size-4" />{label}</button>)}</nav><div className="mt-3 flex min-h-0 flex-1 flex-col border-t border-sidebar-border p-3"><p className="px-3 py-3 text-[11px] font-semibold uppercase tracking-[0.2em] text-muted-foreground">Recent notes</p><div className="flex min-h-0 flex-col gap-1 overflow-y-auto">{notes.slice().sort((a,b) => b.updatedAt-a.updatedAt).slice(0,8).map((note) => <button key={note.id} onClick={() => { onOpenNote(note); onClose() }} className="flex items-center gap-3 px-3 py-2.5 text-left text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-foreground"><FileText className="size-4 shrink-0" /><span className="truncate">{note.title}</span></button>)}</div></div><div className="border-t border-sidebar-border p-4"><p className="text-xs text-muted-foreground">Local-first · Gemini ready</p></div></aside>
}
